[package]
name = "pong"
version = "0.1.0"
authors = ["nhyne <adamjohnson35@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.89.0"
ncollide2d    = "0.19.1"
nalgebra      = "0.18"
nphysics2d    = "0.11.1"
